exp:
  name: 'classifier_mnist'
  experiment_dir: 'experiments/'
model:
  type: 'classifier'
  lr: 0.0002
  beta1: 0.9
  beta2: 0.999
  clipvalue: 10
  clipnorm: 10
trainer:
  num_epochs: 50
  batch_size: 256
  save_checkpoint_freq: 10
  keep_checkpoint_freq: 10
  predict_freq: 5
  use_horovod: true