exp:
  name: 'classifier_mnist'
  experiment_dir: 'experiments/'
model:
  lr: 0.0002
  dropout: true
  beta1: 0.9
  beta2: 0.999
  clipvalue: 10
  clipnorm: 10
trainer:
  num_epochs: 100
  batch_size: 8
  save_checkpoint_freq: 10
  keep_checkpoint_freq: 50
  predicted_dir: 'predicted/'
  predict_freq: 20
  use_horovod: true