exp:
  name: 'gan_mnist'
  experiment_dir: 'experiments/'
model: {}
trainer:
  num_epochs: 200
  batch_size: 4  
  fake_pool_size: 50
  label_smoothing: false
  use_lr_decay: false
  save_checkpoint_freq: 10
  keep_checkpoint_freq: 50
  predict_freq: 20