exp:
  name: 'gan_mnist'
  experiment_dir: 'experiments/'
model:
  type: 'dcgan'
  # --- TEMP ---
  lr: 0.0002
  beta1: 0.9
  beta2: 0.999
  clipvalue: 10
  clipnorm: 10
  # ------------
  generator:
    lr: 0.0001
    # weight_classifier: 1
    # weight_l1: 1
    beta1: 0.9
    clipvalue: 10
    clipnorm: 10
  discriminator:
    lr: 0.0001
    beta1: 0.9
    clipvalue: 10
    clipnorm: 10
trainer:
  num_epochs: 100
  batch_size: 256
  save_checkpoint_freq: 20
  keep_checkpoint_freq: 20
  predict_freq: 5
  use_horovod: true