exp:
  name: 'gan_mnist'
  experiment_dir: 'experiments/'
model:
  generator:
    type: 'dense'
    lr: 0.0002
  discriminator:
    type: 'dense'
    lr: 0.0002
    beta1: 0.9
trainer:
  num_epochs: 200
  batch_size: 128
  save_checkpoint_freq: 10
  keep_checkpoint_freq: 50
  predicted_dir: 'predicted/'
  predict_freq: 20
  use_horovod: true